// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eSoft.Persediaan.Data;

#nullable disable

namespace Accounting.Migrations.DbContextPersediaanMigrations
{
    [DbContext(typeof(DbContextPersediaan))]
    [Migration("20211130074341_initialcreate")]
    partial class initialcreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("eSoft.Persediaan.Model.IcAcct", b =>
                {
                    b.Property<int>("IcAcctId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IcAcctId"), 1L, 1);

                    b.Property<string>("Acct1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Acct2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Acct3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Acct4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Acct5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Acct6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AcctSet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IcAcctId");

                    b.ToTable("IcAccts");
                });

            modelBuilder.Entity("eSoft.Persediaan.Model.IcAltItem", b =>
                {
                    b.Property<int>("IcAltItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IcAltItemId"), 1L, 1);

                    b.Property<string>("AcctSet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("BefNetto")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("CostAwal")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("CostMethod")
                        .HasColumnType("int");

                    b.Property<string>("Divisi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Harga")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("HrgJual")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("HrgNetto")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("ItemCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("JnsBrng")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastNetto")
                        .HasColumnType("datetime2");

                    b.Property<string>("Lokasi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamaItem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Qty")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("QtyPo")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("SaldoAwal")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Satuan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SerialNo")
                        .HasColumnType("bit");

                    b.Property<decimal>("StdPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime?>("TglPost")
                        .HasColumnType("datetime2");

                    b.HasKey("IcAltItemId");

                    b.ToTable("IcAltItems");
                });

            modelBuilder.Entity("eSoft.Persediaan.Model.IcCat", b =>
                {
                    b.Property<int>("IcCatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IcCatId"), 1L, 1);

                    b.Property<string>("Cat1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cat2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cat3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cat4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cat5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cat6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CatCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IcCatId");

                    b.ToTable("IcCats");
                });

            modelBuilder.Entity("eSoft.Persediaan.Model.IcDiv", b =>
                {
                    b.Property<int>("IcDivId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IcDivId"), 1L, 1);

                    b.Property<string>("Divisi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamaDiv")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IcDivId");

                    b.ToTable("IcDivs");
                });

            modelBuilder.Entity("eSoft.Persediaan.Model.IcItem", b =>
                {
                    b.Property<int>("IcItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IcItemId"), 1L, 1);

                    b.Property<string>("AcctSet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("BefNetto")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("CostAwal")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("CostMethod")
                        .HasColumnType("int");

                    b.Property<string>("Divisi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Foto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Harga")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("HrgJual")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("HrgNetto")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("HrgUsd")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("ItemCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("JnsBrng")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastNetto")
                        .HasColumnType("datetime2");

                    b.Property<string>("NamaItem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamaLengkap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Qty")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("QtyPo")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("SaldoAwal")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Satuan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SerialNo")
                        .HasColumnType("bit");

                    b.Property<decimal>("StdPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime?>("TglPost")
                        .HasColumnType("datetime2");

                    b.HasKey("IcItemId");

                    b.ToTable("IcItems");
                });

            modelBuilder.Entity("eSoft.Persediaan.Model.IcLokasi", b =>
                {
                    b.Property<int>("IcLokasiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IcLokasiId"), 1L, 1);

                    b.Property<string>("Alamat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lokasi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamaLokasi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telpon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IcLokasiId");

                    b.ToTable("Iclokasis");
                });

            modelBuilder.Entity("eSoft.Persediaan.Model.IcStockCard", b =>
                {
                    b.Property<int>("IcStockCardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IcStockCardId"), 1L, 1);

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Dokumen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Harga")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("HrgCost")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("ItemCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("JumDpp")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Jumfps")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Jumlah")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Kode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lokasi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MenuApp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Persen")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Qty")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("QtyShp")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Qtybo")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Tanggal")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IcStockCardId");

                    b.ToTable("IcStockCards");
                });

            modelBuilder.Entity("eSoft.Persediaan.Model.IcTransD", b =>
                {
                    b.Property<int>("IcTransDId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IcTransDId"), 1L, 1);

                    b.Property<string>("AcctSet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Harga")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("IcPoTransD")
                        .HasColumnType("int");

                    b.Property<int>("IcTransHId")
                        .HasColumnType("int");

                    b.Property<string>("ItemCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Jumlah")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Kode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lokasi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lokasi2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamaItem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoFaktur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoOrder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoSj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("QtyBo")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("QtyShp")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Satuan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Tanggal")
                        .HasColumnType("datetime2");

                    b.HasKey("IcTransDId");

                    b.HasIndex("IcTransHId");

                    b.ToTable("IcTransDs");
                });

            modelBuilder.Entity("eSoft.Persediaan.Model.IcTransH", b =>
                {
                    b.Property<int>("IcTransHId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IcTransHId"), 1L, 1);

                    b.Property<string>("AcctSet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Keterangan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lokasi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lokasi2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoFaktur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoOrder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoSj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Pajak")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Tanggal")
                        .HasColumnType("datetime2");

                    b.HasKey("IcTransHId");

                    b.ToTable("IcTransHs");
                });

            modelBuilder.Entity("eSoft.Persediaan.Model.IcTransD", b =>
                {
                    b.HasOne("eSoft.Persediaan.Model.IcTransH", "IcTransH")
                        .WithMany("IcTransDs")
                        .HasForeignKey("IcTransHId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IcTransH");
                });

            modelBuilder.Entity("eSoft.Persediaan.Model.IcTransH", b =>
                {
                    b.Navigation("IcTransDs");
                });
#pragma warning restore 612, 618
        }
    }
}
