// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eSoft.Hutang.Data;

#nullable disable

namespace Accounting.Migrations.DbContextHutangMigrations
{
    [DbContext(typeof(DbContextHutang))]
    partial class DbContextHutangModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("eSoft.Hutang.Model.ApAcct", b =>
                {
                    b.Property<int>("ApAcctId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApAcctId"), 1L, 1);

                    b.Property<string>("Acct1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Acct2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Acct3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Acct4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Acct5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Acct6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AcctSet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ApAcctId");

                    b.ToTable("ApAccts");
                });

            modelBuilder.Entity("eSoft.Hutang.Model.ApDist", b =>
                {
                    b.Property<int>("ApDistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApDistId"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dist1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DistCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ApDistId");

                    b.ToTable("ApDists");
                });

            modelBuilder.Entity("eSoft.Hutang.Model.ApHutang", b =>
                {
                    b.Property<int>("ApHutangId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApHutangId"), 1L, 1);

                    b.Property<decimal>("Bayar")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Dokumen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Dpp")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Jumlah")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Keterangan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KodeTran")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Kurs")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("LPB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Nilai")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PPh")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PPn")
                        .HasColumnType("decimal(18,4)");

                    b.Property<bool>("Pajak")
                        .HasColumnType("bit");

                    b.Property<decimal>("Sisa")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("SldBayar")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("SldDisc")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("SldSisa")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("SldUnpl")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Supplier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Tanggal")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("UnApplied")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("ApHutangId");

                    b.ToTable("ApHutangs");
                });

            modelBuilder.Entity("eSoft.Hutang.Model.ApSuppl", b =>
                {
                    b.Property<int>("ApSupplId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApSupplId"), 1L, 1);

                    b.Property<string>("AcctPjk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AcctSet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Alamat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AlmtNPWP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Disc1")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Disc2")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Fax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Hutang")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Kontak")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kurs")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateTime?>("LstOrder")
                        .HasColumnType("datetime2");

                    b.Property<string>("NPWP_Sup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamaLengkap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamaSup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Pajak")
                        .HasColumnType("bit");

                    b.Property<string>("Person")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Provinsi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SldAwal")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Supplier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telpon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Termin")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TglMasuk")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TglPost")
                        .HasColumnType("datetime2");

                    b.HasKey("ApSupplId");

                    b.ToTable("ApSuppls");
                });

            modelBuilder.Entity("eSoft.Hutang.Model.ApTransD", b =>
                {
                    b.Property<int>("ApTransDId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApTransDId"), 1L, 1);

                    b.Property<int>("ApTransHId")
                        .HasColumnType("int");

                    b.Property<decimal>("Bayar")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Bukti")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("DistCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Jumlah")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Keterangan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kode")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("KodeTran")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Lpb")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Sisa")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("Tanggal")
                        .HasColumnType("datetime2");

                    b.HasKey("ApTransDId");

                    b.HasIndex("ApTransHId");

                    b.ToTable("ApTransDs");
                });

            modelBuilder.Entity("eSoft.Hutang.Model.ApTransH", b =>
                {
                    b.Property<int>("ApTransHId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApTransHId"), 1L, 1);

                    b.Property<string>("AcctSet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ApSupplId")
                        .HasColumnType("int");

                    b.Property<decimal>("Bruto")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Bukti")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Hutang")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime?>("JthTempo")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("JumPPh")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("JumPPn")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Jumlah")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("KdBank")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Keterangan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kode")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<decimal>("Kurs")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("NamaSup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Netto")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Nilai")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("NoFaktur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PPh")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PPn")
                        .HasColumnType("decimal(18,4)");

                    b.Property<bool>("Pajak")
                        .HasColumnType("bit");

                    b.Property<string>("Supplier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Tanggal")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Unapplied")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("ApTransHId");

                    b.ToTable("ApTransHs");
                });

            modelBuilder.Entity("eSoft.Hutang.Model.ApTransD", b =>
                {
                    b.HasOne("eSoft.Hutang.Model.ApTransH", "ApTransH")
                        .WithMany("ApTransDs")
                        .HasForeignKey("ApTransHId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApTransH");
                });

            modelBuilder.Entity("eSoft.Hutang.Model.ApTransH", b =>
                {
                    b.Navigation("ApTransDs");
                });
#pragma warning restore 612, 618
        }
    }
}
