// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eSoft.Company.Data;

#nullable disable

namespace Accounting.Migrations.DbContextCompanyMigrations
{
    [DbContext(typeof(DbContextCompany))]
    [Migration("20211231050151_initialcompany")]
    partial class initialcompany
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("eSoft.Company.Model.CoSetup", b =>
                {
                    b.Property<int>("CoSetupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CoSetupId"), 1L, 1);

                    b.Property<string>("Account1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Account2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Account3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Account4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Account5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Account6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoKode")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("CoName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CoSetupId");

                    b.ToTable("CoSetups");
                });
#pragma warning restore 612, 618
        }
    }
}
