// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eSoft.Penjualan.Data;

#nullable disable

namespace Accounting.Migrations.DbContextJualMigrations
{
    [DbContext(typeof(DbContextJual))]
    [Migration("20211130074311_initialcreate")]
    partial class initialcreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("eSoft.Penjualan.Model.OeTransD", b =>
                {
                    b.Property<int>("OeTransDId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OeTransDId"), 1L, 1);

                    b.Property<string>("AcctSet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Customer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Harga")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("HrgCost")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("ItemCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("JumDpp")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Jumlah")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Kode")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Lokasi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamaItem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoLpb")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OeTransHId")
                        .HasColumnType("int");

                    b.Property<decimal>("Persen")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Qty")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("QtyBo")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Satuan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Tanggal")
                        .HasColumnType("datetime2");

                    b.HasKey("OeTransDId");

                    b.HasIndex("OeTransHId");

                    b.ToTable("OeTransDs");
                });

            modelBuilder.Entity("eSoft.Penjualan.Model.OeTransH", b =>
                {
                    b.Property<int>("OeTransHId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OeTransHId"), 1L, 1);

                    b.Property<string>("AlamatKirim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cek")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Customer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DPayment")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("JthTempo")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Jumlah")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Keterangan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kode")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("Lokasi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamaCust")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoLpb")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoPrj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoSJ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Ongkos")
                        .HasColumnType("decimal(18,4)");

                    b.Property<bool>("Pajak")
                        .HasColumnType("bit");

                    b.Property<decimal>("Ppn")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PpnPersen")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("QtyTerima")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Tagihan")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("Tanggal")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalQty")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("TtlJumlah")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("OeTransHId");

                    b.ToTable("OeTransHs");
                });

            modelBuilder.Entity("eSoft.Penjualan.Model.OeTransD", b =>
                {
                    b.HasOne("eSoft.Penjualan.Model.OeTransH", "OeTransH")
                        .WithMany("OeTransDs")
                        .HasForeignKey("OeTransHId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OeTransH");
                });

            modelBuilder.Entity("eSoft.Penjualan.Model.OeTransH", b =>
                {
                    b.Navigation("OeTransDs");
                });
#pragma warning restore 612, 618
        }
    }
}
