// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eSoft.Asset.Data;

#nullable disable

namespace Accounting.Migrations
{
    [DbContext(typeof(DbContextAssets))]
    partial class DbContextAssetsModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("eSoft.Asset.Model.AsAcctset", b =>
                {
                    b.Property<int>("AsAcctId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AsAcctId"), 1L, 1);

                    b.Property<string>("Acct1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Acct2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Acct3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Acct4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Acct5")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Acct6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AcctSet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AsAcctId");

                    b.ToTable("AsAcctsets");
                });

            modelBuilder.Entity("eSoft.Asset.Model.AsAssets", b =>
                {
                    b.Property<int>("AsAssetsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AsAssetsId"), 1L, 1);

                    b.Property<string>("Acctset")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Administrasi")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("AsItemCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Asuransi")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("BarcodeAssets")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Bunga")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("DistCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("JatuhTempo")
                        .HasColumnType("datetime2");

                    b.Property<string>("Merek")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamaBarang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Nilai")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("NilaiTerjual")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("NoMesin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoPol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoRangka")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PPn")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Penyusutan")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Provisi")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.Property<decimal>("SisaNilai")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Termin")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("TglBeli")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TglJual")
                        .HasColumnType("datetime2");

                    b.HasKey("AsAssetsId");

                    b.ToTable("AsAssetss");
                });

            modelBuilder.Entity("eSoft.Asset.Model.AsDistSet", b =>
                {
                    b.Property<int>("AsDistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AsDistId"), 1L, 1);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dist1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DistCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AsDistId");

                    b.ToTable("AsDistSets");
                });

            modelBuilder.Entity("eSoft.Asset.Model.AsDivisi", b =>
                {
                    b.Property<int>("AsDivId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AsDivId"), 1L, 1);

                    b.Property<string>("Divisi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamaDiv")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AsDivId");

                    b.ToTable("AsDivisis");
                });

            modelBuilder.Entity("eSoft.Asset.Model.AsItem", b =>
                {
                    b.Property<int>("AsItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AsItemId"), 1L, 1);

                    b.Property<string>("Divisi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamaItem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Satuan")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AsItemId");

                    b.ToTable("AsItems");
                });

            modelBuilder.Entity("eSoft.Asset.Model.AsTransaksi", b =>
                {
                    b.Property<int>("AsTransaksiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AsTransaksiId"), 1L, 1);

                    b.Property<string>("BarcodeAssets")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Nilai")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("Tanggal")
                        .HasColumnType("datetime2");

                    b.HasKey("AsTransaksiId");

                    b.ToTable("AsTransaksis");
                });
#pragma warning restore 612, 618
        }
    }
}
